name: lawnchair

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cloning lawnchair repo 
        run: git clone --depth=1 https://github.com/LawnchairLauncher/lawnchair
      
      - name: Dowloading latest debug apk & sending it to telegram
        run: |
          cd lawnchair
          gh run download $(gh run list -L 1 > id1.txt && awk '{print $12}' id1.txt)
          cd "Debug APK"
          for f in *\ *; do mv "$f" "${f// /_}"; done
          curl -F document=@$(ls -U *.apk) -F chat_id="-1001213452785" "https://api.telegram.org/bot$token/sendDocument"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.TELEGRAM_CI_BOT_TOKEN }}
